name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          path: uluwatuxyz

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: cd uluwatuxyz && hugo --minify --baseURL https://www.uluwatu.xyz/ && echo "www.uluwatu.xyz" > CNAME


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: uluwatuxyz/public